Run gradle build

Welcome to Gradle 9.7.1!

Here are the highlights of this release:
 - Isolated Projects graduates to incubating
 - Broader Configuration Cache compatibility
 - Resilient Sync helps you fix broken builds
 - More source locations in problem reports

For more details see https://docs.gradle.org/9.7.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.
[Incubating] Problems report is available at: file:///home/runner/work/azarasi-music-mod/azarasi-music-mod/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

* Where:
Build file '/home/runner/work/azarasi-music-mod/azarasi-music-mod/build.gradle' line: 14


You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/9.7.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
* What went wrong:
A problem occurred evaluating root project 'azarasi-music-mod'.
> Plugin with id 'net.fabricmc.loom' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 16s
Error: Process completed with exit code 1.
